
export class Constants {

  static BEGINNER_DIFFICULTY = 'BEGINNER';
  static NOVICE_DIFFICULTY = 'NOVICE';
  static ADVANCED_DIFFICULTY = 'ADVANCED';
  static EXPERT_DIFFICULTY = 'EXPERT';

  static ALL_DIFFICULTIES = [
    Constants.BEGINNER_DIFFICULTY,
    Constants.NOVICE_DIFFICULTY,
    Constants.ADVANCED_DIFFICULTY,
    Constants.EXPERT_DIFFICULTY
  ];

  static QUEUE_EMPTY = 'QUEUE_EMPTY';
  static QUEUE_SATISFIED = 'QUEUE_SATISFIED';
  static QUEUE_NOT_SATISFIED = 'QUEUE_NOT_SATISFIED';
  static QUEUE_CRITICAL = 'QUEUE_CRITICAL';
  static QUEUE_FULL = 'QUEUE_FULL';
}
