
export class Constants {

  static UNSOLVABLE_GAME = 'UNSOLVABLE';
  static EASY_DIFFICULTY = 'EASY';
  static MEDIUM_DIFFICULTY = 'MEDIUM';
  static HARD_DIFFICULTY = 'HARD';
  static EVIL_DIFFICULTY = 'EVIL';

  static ALL_DIFFICULTIES = [
    Constants.EASY_DIFFICULTY,
    Constants.MEDIUM_DIFFICULTY,
    Constants.HARD_DIFFICULTY,
    Constants.EVIL_DIFFICULTY
  ];

  static QUEUE_EMPTY = 'QUEUE_EMPTY';
  static QUEUE_SATISFIED = 'QUEUE_SATISFIED';
  static QUEUE_NOT_SATISFIED = 'QUEUE_NOT_SATISFIED';
  static QUEUE_CRITICAL = 'QUEUE_CRITICAL';
  static QUEUE_FULL = 'QUEUE_FULL';

  static GEN_ONE_PATTERN = 77586305296;

  static ARROW_UP = 'UP';
  static ARROW_DOWN = 'DOWN';
  static ARROW_LEFT = 'LEFT';
  static ARROW_RIGHT = 'RIGHT';
}
